### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by dtmoodie** [madplotlib/madplotlib#1]
Hi,

Your todo list lists "* Rethink the approach to support a variable number of parameters for plot();"
Would named parameters be useful? 
Implementation: https://github.com/dtmoodie/MetaObject/blob/master/modules/params/src/MetaObject/params/NamedParam.hpp

Example: 
https://github.com/dtmoodie/MetaObject/blob/master/tests/test_named_parameter/main.cpp

**Comment by karlphillip** [comment]
Hi, thanks for your suggestion. 

Right now I am taking a look at alternatives that are not going to depend on external libraries so I can keep this library short and sweet.

I see `#include <boost/optional.hpp>`. Does it really need Boost?

**Comment by dtmoodie** [comment]
No it doesn't need boost. I just use boost optional a lot in my library so I have the option of passing in a boost optional value. 
If you like this idea I can make an implementation without boost as a PR.

**Comment by karlphillip** [comment]
I really really like it!

It would be great to be able to call plot() like:
`plot(marker="o", alpha=0.5f, color=QColor(0xFF0000),  linewidth=4, markersize=1.5f);`

**Comment by dtmoodie** [comment]
Cool, I can totally do that.  
I will likely have to do something like _marker=, _alpha=, _color=... etc to maintain uniqueness.
